contentful:
  spaces:
    - isabelmireles:
        space: mdb7wi33n4kq
        access_token: 6l2-rWQXhvDLkY4zH5M8XT51ytJS548Q6bQ0QfD9f8s

plugins:
  - jekyll-datapage-generator


sass:
  sass_dir: assets/css
